import asyncio, os, re, shutil, subprocess, time, httpx

from concurrent.futures import ThreadPoolExecutor

try:
        import ujson as json
except ModuleNotFoundError:
        import json

from pathlib import Path
from typing import List, Optional, Set, Tuple
from urllib.parse import parse_qs, unquote, urlparse

from yt_dlp import YoutubeDL
from yt_dlp.utils import DownloadError

from nonebot import logger, on_command, on_message
from nonebot.adapters.onebot.v11 import (
    MessageSegment,
    Message,
    MessageEvent,
    GroupMessageEvent,
    ActionFailed,
)
from nonebot.params import CommandArg
from nonebot.permission import SUPERUSER
from nonebot.plugin import get_plugin_config, PluginMetadata

from .config import Config
from .utils import is_number, err_info



usage = '''

b2v:
    -s  插件开关
    -c  设置cookies  # 至少需要包含 SESSDATA, bili_jct, DedeUserID, buvid3/buvid4
    -p  设置清晰度  # 360/480/720/1080, 0 为不限制
    -x  设置文件限制  # 默认 72 (MB), 0 为不限制
    -l  查看列表
    -r  重置列表

'''.strip()


__plugin_meta__ = PluginMetadata(
    name="B链解析",
    description="将群友分享的B站链接解析为 mp4",
    usage=usage,
    type="application",
    config=Config,
    supported_adapters={"~onebot.v11"},
)


def ffmpeg_dir():
    ff = shutil.which("ffmpeg")
    if not ff:
        logger.error("ffmpeg not found")
        raise FileNotFoundError("ffmpeg not found")
    return f"{Path(ff).parent}"


def ffprobe():
    ff = shutil.which("ffprobe")
    if not ff:
        logger.error("ffprobe not found")
        raise FileNotFoundError("ffprobe not found")
    return ff


DATA_DIR: Path = Path() / "data" / "bv2mp4"
DATA_DIR.mkdir(parents=True, exist_ok=True)


COOKIES_FILE: Path = DATA_DIR / 'cookies.json'
STATE_FILE: Path = DATA_DIR / 'state.json'


BV_DIR: Path = Path(get_plugin_config(Config).bv_cache)
BV_DIR.mkdir(parents=True, exist_ok=True)


MAX_WORKERS: str = f"{get_plugin_config(Config).bv_max_workers}"


# 域名匹配
BILI_URL_RE = re.compile(
    r"(https?://(?:[\w-]+\.)?(?:bilibili\.com|b23\.tv)/[^\s\"'<>]+)",
    flags=re.IGNORECASE,
)


# =========================
# 设置存取
# =========================

_bv_state: dict = (
    json.loads(STATE_FILE.read_text("utf-8"))
    if STATE_FILE.is_file()
    else {
        "group": [],
        "max_height": 0,
        "maxsize": 72
    }
)
def _save_state() -> None:
    STATE_FILE.write_text(
        json.dumps(
            _bv_state, indent=2, ensure_ascii=False
        ), "utf-8"
    )


# =========================
# cookies存取
# =========================

_bv_cookies: dict = {
    "cookies": COOKIES_FILE.read_text("utf-8")
    if COOKIES_FILE.is_file() else ""
}
def _save_cookies() -> None:
    COOKIES_FILE.write_text(_bv_cookies["cookies"], "utf-8")


def _ensure_cookiefile(cookie_string: str) -> Optional[str]:
    """
    将 Cookie 字符串转为 Netscape 格式，供 yt-dlp 使用。
    """
    if not cookie_string:
        return None

    pairs = []
    for part in cookie_string.split(";"):
        part = part.strip()
        if "=" not in part:
            continue
        k, v = part.split("=", 1)
        if k and v:

            pairs.append((k.strip(), v.strip()))

    if not pairs:
        return None

    expiry = int(time.time()) + 180 * 24 * 3600
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by bv2mp4",
        "",
    ]

    for k, v in pairs:
        # domain include_subdomains path secure expiry name value
        lines.append(f".bilibili.com\tTRUE\t/\tFALSE\t{expiry}\t{k}\t{v}")

    try:
        _bv_cookies["cookies"] = "\n".join(lines)+"\n" 
        _save_cookies()
        return f"{COOKIES_FILE}"
    except Exception as e:
        logger.error(f"bv2mp4: {e}")
        return None


# =========================
# URLs 提取
# =========================

def _find_urls_in_text(text: str) -> List[str]:
    urls = list()
    for m in BILI_URL_RE.findall(text or ""):
        if m not in urls:
            urls.append(m)
    try:
        parsed = urlparse(text)
        if parsed and parsed.query:
            qs = parse_qs(parsed.query)
            for key in ("url", "qqdocurl", "jumpUrl", "webpageUrl"):
                for v in qs.get(key, []):
                    v = unquote(v)
                    for u in BILI_URL_RE.findall(v):
                        if u not in urls:
                            urls.append(u)
    except Exception as e:
        logger.debug(f"bv2mp4: {e}")
        pass
    return urls


def _walk_strings(obj) -> List[str]:
    out: List[str] = []
    try:
        if isinstance(obj, dict):
            for v in obj.values():
                out.extend(_walk_strings(v))
        elif isinstance(obj, list):
            for it in obj:
                out.extend(_walk_strings(it))
        elif isinstance(obj, str):
            out.append(obj)
    except Exception as e:
        logger.debug(f"bv2mp4: {e}")
        pass
    return out


def _extract_bili_urls_from_event(event: MessageEvent) -> List[str]:
    urls = list()
    try:
        for seg in event.message:
            # 1) 纯文本
            if seg.type == "text":
                txt = seg.data.get("text", "")
                for u in _find_urls_in_text(txt):
                    if u not in urls:
                        urls.append(u)
            # 2) JSON 卡片
            elif seg.type == "json":
                raw = seg.data.get("data") or seg.data.get("content") or ""
                for u in _find_urls_in_text(raw):
                    if u not in urls:
                        urls.append(u)
                try:
                    obj = json.loads(raw)
                    for s in _walk_strings(obj):
                        for u in _find_urls_in_text(s):
                            if u not in urls:
                                urls.append(u)
                except Exception:
                    pass
            # 3) XML 卡片
            elif seg.type == "xml":
                raw = seg.data.get("data") or seg.data.get("content") or ""
                for u in _find_urls_in_text(raw):
                    if u not in urls:
                        urls.append(u)
            # 4) 分享卡片
            elif seg.type == "share":
                u = seg.data.get("url") or ""
                for u2 in _find_urls_in_text(u):
                    if u2 not in urls:
                        urls.append(u2)
            else:
                s = str(seg)
                for u in _find_urls_in_text(s):
                    if u not in urls:
                        urls.append(u)
    except Exception as e:
        logger.debug(f"bv2mp4: {e}")
        pass
    return urls


# =========================
# Call API
# =========================

def _build_browser_like_headers() -> dict:
    return {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/150.0.0.0 Safari/537.36"
        ),
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
        "Referer": "https://www.bilibili.com/",
        "Origin": "https://www.bilibili.com",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
        "Sec-Fetch-Site": "same-origin",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Dest": "document",
    }


def _expand_short_url(u: str, timeout: float = 8.0) -> str:
    try:
        host: str = urlparse(u).hostname or ""
        if host.lower() not in {"b23.tv", "www.b23.tv"}:
            return u
        
        hdrs: dict[str, str] = {
            "User-Agent": _build_browser_like_headers()["User-Agent"],
            "Referer": "https://www.bilibili.com/",
        }
        
        try:
            with httpx.Client(
                headers=hdrs,
                follow_redirects=True,
                timeout=timeout,
            ) as client:
                resp = client.head(u)
                return str(resp.url) or u
        except Exception:
            try:
                with httpx.Client(
                    headers=hdrs,
                    follow_redirects=True,
                    timeout=timeout,
                ) as client:
                    resp = client.get(u)
                    return str(resp.url) or u
            except Exception:
                return u

    except Exception as e:
        logger.debug(f"bv2mp4: 短链展开失败, 使用原链接 ({u}): {e}")
        return u


def _check_video_file(path: str) -> bool:
    """检查视频文件大小和分辨率"""
    try:
        # 检查文件大小
        path_obj = Path(path)
        if _bv_state["maxsize"] and path_obj.exists():
            size_mb = path_obj.stat().st_size / (1024 * 1024)
            if size_mb > _bv_state["maxsize"]:
                path_obj.unlink()
                return False

        # 检查视频分辨率
        args: Tuple = (
                ffprobe(),
                "-v",
                "error",
                "-select_streams",
                "v:0",
                "-show_entries",
                "stream=width,height",
                "-of",
                "csv=p=0",
                path,
        )
        result = subprocess.run(
            args,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            try:
                _, height = result.stdout.strip().split(",")
                # 检查是否设置了高度限制
                if _bv_state["max_height"] and int(height) > _bv_state["max_height"]:
                    path_obj.unlink()
                    return False
            except ValueError:
                pass
        return True
    except Exception:
        return False


def _build_format_candidates(height_limit: int) -> List[str]:
    """构建格式候选列表"""
    h = height_limit if height_limit and height_limit > 0 else None

    if not h:
        return ["bv*+ba/best"]

    # 根据清晰度限制构建格式候选
    format_map = {
        1080: [
            f"bv*[height>=1080]+ba/best",
            f"bv*[height>=720]+ba/best",
            "bv*+ba/best",
        ],
        720: [f"bv*[height>=720]+ba/best", f"bv*[height>=480]+ba/best", "bv*+ba/best"],
        480: [f"bv*[height>=480]+ba/best", "bv*+ba/best"],
    }

    # 根据高度选择最适合的格式列表
    for threshold, formats in sorted(format_map.items(), reverse=True):
        if h >= threshold:
            return formats

    # 默认格式
    return ["bv*+ba/best"]


def format_selector(ctx):
    """ Select the best video and the best audio that won't result in an mkv.
    NOTE: This is just an example and does not handle all cases """

    # formats are already sorted worst to best
    formats = ctx.get('formats')[::-1]

    # acodec='none' means there is no audio
    best_video = next(f for f in formats
                      if f['vcodec'] != 'none' and ("avc" in f['vcodec'] or "hvc" in f['vcodec']) and f['acodec'] == 'none')

    # find compatible audio extension
    audio_ext = {'mp4': 'm4a', 'webm': 'webm'}[best_video['ext']]
    # vcodec='none' means there is no video
    best_audio = next(f for f in formats if (
        f['acodec'] != 'none' and f['vcodec'] == 'none' and f['ext'] == audio_ext))

    # These are the minimum required fields for a merged format
    yield {
        'format_id': f'{best_video["format_id"]}+{best_audio["format_id"]}',
        'ext': best_video['ext'],
        'requested_formats': [best_video, best_audio],
        # Must be + separated list of protocols
        'protocol': f'{best_video["protocol"]}+{best_audio["protocol"]}'
    }

def _download_with_ytdlp(url: str) -> Tuple[str, str]:

    final_url = _expand_short_url(url)

    # 构建 Cookie 文件
    candidates = _build_format_candidates(_bv_state["max_height"])
    last_err: Optional[Exception] = None

    for _, _ in enumerate(candidates):
        headers = _build_browser_like_headers()
        ydl_opts = {
            "format": format_selector,
            "outtmpl": str(BV_DIR / "%(title).80s [%(id)s].%(ext)s"),
            "noplaylist": True,
            "merge_output_format": "mp4",
            "quiet": False,
            "no_warnings": False,
            "max_filesize" : _bv_state["maxsize"] * 1024 * 1024,  # MB to Bytes
            "http_headers": headers,
            "extractor_args": {
                "bili": {
                    "player_client": ["android", "web"],
                    "lang": ["zh-CN"],
                }
            }
        }

        ydl_opts["ffmpeg_location"] = ffmpeg_dir()
        ydl_opts["cookiefile"] = COOKIES_FILE

        try:
            with YoutubeDL(ydl_opts) as ydl:  #type: ignore
                info = ydl.extract_info(final_url, download=True)
                title = info.get("title") or "B站视频"

                # 获取下载信息
                height = info.get("height", 0)
                logger.info(f"bv2mp4: 下载完成: {title} ({height}p)")

                # 定位文件
                final_path = _locate_final_file(ydl, info)
                if not final_path or not Path(final_path).exists():
                    logger.warning(e := "bv2mp4: 未找到已下载的视频文件，可能未安装 ffmpeg")
                    raise RuntimeError(e)
                return final_path, title
        except DownloadError as e:
            last_err = e
            continue
        except Exception as e:
            last_err = e
            continue

    if last_err:
        logger.warning(e := f"bv2mp4: {last_err}")
        raise RuntimeError(e)

    logger.warning(e := "bv2mp4: 未知错误, 无法下载该视频")
    raise RuntimeError(e)


def _locate_final_file(ydl, info) -> Optional[str]:
    for key in ("requested_downloads", "requested_formats"):
        arr = info.get(key)
        if isinstance(arr, list):
            for it in arr:
                fp = it.get("filepath")
                if fp and os.path.exists(fp):
                    return fp
    for key in ("filepath", "_filename"):
        fp = info.get(key)
        if fp and Path(fp).exists():
            return fp
    # 预测合并后 mp4
    base = ydl.prepare_filename(info)
    root = Path(base).stem
    candidate = root + ".mp4"
    if Path(candidate).exists():
        return candidate
    # 兜底：按视频ID在目录中搜
    vid = info.get("id") or ""
    if vid:
        try:
            files = [BV_DIR / f.name for f in Path(BV_DIR).iterdir() if vid in f.name]
            if files:
                files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
                return str(files[0])
        except Exception:
            pass
    return None


_ytdlp_executor = ThreadPoolExecutor(
    max_workers = int(MAX_WORKERS)
    if is_number(MAX_WORKERS) else 4
)


async def _get_down(url):
    loop = asyncio.get_running_loop()

    return await loop.run_in_executor(
        _ytdlp_executor,
        _download_with_ytdlp,
        url,
    )


# =========================
# 事件监听
# =========================

_processing: Set[str] = set()

msg_listen = on_message(priority=15, block=False)

@msg_listen.handle()
async def _(event: GroupMessageEvent):

    group_id = f"{event.group_id}"
    if not group_id in _bv_state["group"]:
        return

    urls = _extract_bili_urls_from_event(event)
    if not urls:
        logger.debug(f"bv2mp4: 消息中未发现B链")
        return

    url = urls[0]
    key = f"{group_id}|{url}"
    if key in _processing:
        logger.debug(f"bv2mp4: 已在处理，忽略重复: {key}")
        return
    _processing.add(key)
    logger.info(f"bv2mp4: 检测到B链")

    try:
        path, title = await _get_down(url)
    except (ImportError, RuntimeError) as e:
        logger.error(f"bv2mp4: 下载环境异常: {e}")
        return
    except Exception as e:
        logger.error(f"bv2mp4: 下载异常: {e}")
        return

    # 检查文件大小和分辨率
    if not _check_video_file(path):
        logger.debug("bv2mp4: 文件超出限制, 停止转发")
        return

    _processing.discard(key)

    try:
        await msg_listen.send(
            message=MessageSegment.video(file=path)
            + Message(f"\n{title or 'B站视频'}"),
        )
    except ActionFailed as e:
        logger.error(f"bv2mp4: {err_info(e)}")
        raise e
    finally:
        try:
            if (path_obj := Path(path)).exists():
                path_obj.unlink()
        except Exception as e:
            logger.warning(f"Failed to delete temp file {path}: {e}")


# =========================
# 插件控制
# =========================

def _set_group(args: str, event: MessageEvent) -> str:

    add_list, del_list = [], []

    if oi := args.strip().split():
        gids = list(set([gid for gid in oi if is_number(gid)]))

        add_list = [i for i in gids if not i in _bv_state["group"]]
        del_list = list(set(gids) & set(_bv_state["group"]))

        _bv_state["group"] = [i for i in _bv_state["group"] if i not in del_list]
        _bv_state["group"].extend(add_list)

        _save_state()

        return ''.join([
            f"B链解析:\n",
            f"新增{len(add_list)}个群聊: {add_list}\n" if add_list else '',
            f"取消{len(del_list)}个群聊: {del_list}\n" if del_list else ''
        ])

    if isinstance(event, GroupMessageEvent):
        if (gid := str(event.group_id)) in _bv_state["group"]:
            _bv_state["group"].pop(gid)
            _save_state()
            return "B链解析已禁用"
        else:
            _bv_state["group"].append(gid)
            _save_state()
            return "B链解析已启用"

    return "群号必须为数字!"


def _set_cookies(args, *_) -> str:
    if _ensure_cookiefile(args.strip()):
        return "已配置 bili cookies"
    return "未能正确配置cookies, 请检查cookies格式"


def _set_quality(args, *_) -> str:

    if is_number(size := args.strip()) and int(size) >= 0:

        _bv_state["max_height"] = int(size)
        _save_state()

        return "已取消清晰度限制" if _bv_state["max_height"] == 0 else f"已限制视频清晰度 {_bv_state['max_height']}"

    return '参数必须为大于或等于0的数字!'


def _set_maxsize(args, *_) -> str:

    if is_number(size := args.strip()) and int(size) >= 0:

        _bv_state["maxsize"] = int(size)
        _save_state()

        return "已取消文件限制" if _bv_state["maxsize"] == 0 else f"已限制文件大小 {_bv_state['maxsize']}MB"

    return '参数必须为大于或等于0的数字!'


def _get_list(*_):
    return f"B链解析: 已启用\n{len(_bv_state['group'])}个群聊:\n{_bv_state['group']}" if _bv_state["group"] else "未启用B链解析"


def _clear_list(*_) -> str:
    _bv_state["group"].clear()
    _save_state()
    return "列表已重置"


_ctrl_dict = {
    "s": _set_group,
    "c": _set_cookies,
    "p": _set_quality,
    "x": _set_maxsize,
    "l": _get_list,
    "r": _clear_list,
}


def handle_msg(
    event,
    arg,
) -> str:
    msg = arg.extract_plain_text().strip()

    if not (msg and msg[1:] and msg.startswith("-")):
        return usage

    if (s := msg[1:2]) in list(_ctrl_dict):
        return _ctrl_dict[s](msg[2:], event)

    return usage


bv_control = on_command('b2v', permission=SUPERUSER, priority=2, block=True)

@bv_control.handle()
async def _(event: MessageEvent, arg: Message = CommandArg()):
    await bv_control.finish(handle_msg(event, arg), reply_message=True)
